# golangci-lint v2 configuration
# Documentation: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor/
    - internal/mocks
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  # Linter-specific settings
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      # Allow ignoring defer cleanup in tests
      - (os\\.)?Remove(All)?
      - (os\\.)?Unsetenv
    disable-default-exclusions: false

  govet:
    enable-all: true
    disable:
      - fieldalignment # Can be noisy for structs
      - shadow        # Often false positives
    check-shadowing: true

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: false

  gocyclo:
    min-complexity: 15

  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true

  goconst:
    min-len: 2
    min-occurrences: 2

  misspell:
    locale: US

  lll:
    line-length: 120

  funlen:
    lines: 80
    statements: 50

  nestif:
    min-complexity: 5

  godot:
    scope: declarations
    capital: false

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  goimports:
    local-prefixes: github.com/MayukhSobo/scaffold

  nolintlint:
    allow-leading-space: true # don't require nolint directives to be preceded by comments
    allow-unused: false # report unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being silenced

  stylecheck:
    checks: ["all", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - exportloopref
    - tenv
    - durationcheck
    - usestdlibvars
    - reassign
    - prealloc
    - predeclared
    - promlinter
    - contextcheck

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - tmp
    - reports

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gocritic
        - gocyclo
        - dupl

    # Allow long lines in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll

    # Allow TODO comments in development
    - text: "Line contains TODO"
      linters:
        - godox

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false 