# golangci-lint v2 configuration
# Documentation: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - tmp
    - reports
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  # Linter-specific settings
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      # Allow ignoring defer cleanup in tests
      - (os\\.)?Remove(All)?
      - (os\\.)?Unsetenv
    disable-default-exclusions: false

  govet:
    enable-all: true
    disable:
      - fieldalignment # Can be noisy for structs
      - shadow        # Often false positives

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: false

  gocyclo:
    min-complexity: 15

  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  funlen:
    lines: 80
    statements: 50

  nestif:
    min-complexity: 5

  godot:
    scope: declarations
    capital: false

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

linters:
  enable:
    # Default/Core linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Code quality
    - gocyclo
    - cyclop
    - goconst
    - revive
    - godot
    - funlen
    - nestif
    
    # Bug detection
    - bodyclose
    - contextcheck
    - errorlint
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    
    # Performance
    - prealloc
    - unconvert
    - unparam
    
    # Style/Format
    - misspell
    - lll
    - nakedret
    - whitespace

  disable:
    # Too strict for general use
    - gochecknoinits
    - gochecknoglobals
    - exhaustive
    - exhaustruct
    - varnamelen
    - wrapcheck
    - nlreturn
    - wsl
    - mnd
    - godox

  fast: false

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - tmp
    - reports

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocyclo
        - cyclop
        - errcheck
        - funlen
        - nestif
        - bodyclose
        - contextcheck

    # Allow long lines in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll

    # Allow TODO comments in development
    - text: "Line contains TODO"
      linters:
        - godox

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false 