services:
  mysql:
    image: mysql:8.0
    container_name: scaffold-mysql
    environment:
      MYSQL_ROOT_PASSWORD: bXlfc2VjdXJlX3Bhc3N3b3JkXzEyMw==
      MYSQL_DATABASE: user
      MYSQL_USER: scaffold
      MYSQL_PASSWORD: bXlfc2VjdXJlX3Bhc3N3b3JkXzEyMw==
    ports:
    - 3306:3306
    volumes:
    - mysql_data:/var/lib/mysql
    - ./db/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
    - ./scripts/docker/mysql-entrypoint.sh:/scripts/docker/mysql-entrypoint.sh:ro
    entrypoint:
    - ./scripts/docker/mysql-entrypoint.sh
    - mysqld
  adminer:
    image: adminer:latest
    container_name: scaffold-adminer
    ports:
    - 8888:8080
    depends_on:
    - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
  app:
    build: .
    container_name: scaffold-app
    ports:
    - 12001:8000
    depends_on:
    - mysql
    volumes:
    - ./configs:/app/configs
    - ./logs:/app/logs
    command:
    - ./server
    - --config=configs/docker.yml
volumes:
  mysql_data: null
