version: "3"

# Include all task files from the tasks directory
includes:
  build: ./tasks/build.yml
  dev: ./tasks/dev.yml
  test: ./tasks/test.yml
  quality: ./tasks/quality.yml
  deps: ./tasks/deps.yml
  clean: ./tasks/clean.yml
  docker: ./tasks/docker.yml
  config: ./tasks/config.yml
  help: ./tasks/help.yml

vars:
  APP_NAME: Scaffold
  DOCKER_IMAGE_NAME: scaffold  # Lowercase version for Docker
  BUILD_DIR: build
  CMD_DIR: cmd/server
  CONFIG_DIR: configs

  # Binary naming configuration
  BINARY_BASE_NAME: scaffold
  BINARY_NAME: "{{.BINARY_BASE_NAME}}"

  # Release binary naming: [BINARY_BASE_NAME]-[ARCH]-[PLATFORM]
  BINARY_LINUX: "{{.BINARY_BASE_NAME}}-amd64-linux"
  BINARY_DARWIN: "{{.BINARY_BASE_NAME}}-amd64-darwin"
  BINARY_WINDOWS: "{{.BINARY_BASE_NAME}}-amd64-windows.exe"
  BINARY_DEBUG: "{{.BINARY_BASE_NAME}}"

  GO_VERSION: 1.24.3
  GOLANGCI_LINT_VERSION: v2.2.1
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "v1.0.0"
  BUILD_TIME:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  # Test directories - modify this to add/remove directories from testing
  TEST_DIRS: ./cmd/... ./pkg/...
  # Coverage output directory
  COVERAGE_DIR: reports

env:
  CGO_ENABLED: 1
  GOOS: "{{OS}}"
  GOARCH: "{{ARCH}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
    - task --list
    silent: true
