version: "3"

tasks:
  # Utility tasks
  all:
    desc: Clean all build artifacts and caches
    silent: true
    cmds:
    - task shared:cleanup:build
    - task shared:cleanup:go
    - task shared:cleanup:reports
    - echo "✅ All artifacts and caches cleaned"

  debug:
    desc: Clean development build artifacts only
    silent: true
    cmds:
    - rm -rf {{.BUILD_DIR}}/debug
    - echo "Development build artifacts cleaned"

  release:linux:
    desc: Clean Linux release build artifacts only
    silent: true
    cmds:
    - rm -rf {{.BUILD_DIR}}/linux
    - echo "Linux release build artifacts cleaned"

  release:darwin:
    desc: Clean macOS release build artifacts only
    silent: true
    cmds:
    - rm -rf {{.BUILD_DIR}}/darwin
    - echo "macOS release build artifacts cleaned"

  release:windows:
    desc: Clean Windows release build artifacts only
    silent: true
    cmds:
    - rm -rf {{.BUILD_DIR}}/windows
    - echo "Windows release build artifacts cleaned"

  release:all:
    desc: Clean all release build artifacts
    silent: true
    cmds:
    - rm -rf {{.BUILD_DIR}}/linux
    - rm -rf {{.BUILD_DIR}}/darwin
    - rm -rf {{.BUILD_DIR}}/windows
    - echo "All release build artifacts cleaned" 