version: "3"

tasks:
  # Code quality tasks
  lint:
    desc: "Run linter (use skip=true to skip installation, or force=true to reinstall)"
    silent: true
    cmds:
      - |
        SKIP_INSTALL={{.skip}}
        FORCE={{.force}}
        
        INSTALL_LINT=true
        if [ "$SKIP_INSTALL" = "true" ]; then
          INSTALL_LINT=false
        fi

        if [ "$INSTALL_LINT" = "true" ] && [ "$FORCE" != "true" ]; then
          if command -v golangci-lint &>/dev/null && [ "$(golangci-lint --version 2>/dev/null | awk -F'version ' '{print $2}' | awk '{print $1}')" = "$(echo "{{.GOLANGCI_LINT_VERSION}}" | sed 's/v//')" ]; then
            INSTALL_LINT=false
          fi
        fi

        if [ "$INSTALL_LINT" = "true" ]; then
          echo "Installing golangci-lint@{{.GOLANGCI_LINT_VERSION}}..."
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        fi
        
        golangci-lint run

  fmt:
    desc: Format code
    silent: true
    cmds:
    - go fmt ./...
    - echo "Code formatted successfully"

  vet:
    desc: Run go vet
    silent: true
    cmds:
    - go vet ./...
    - echo "Vet analysis completed"

  check:
    desc: Run all code quality checks
    silent: true
    cmds:
    - go fmt ./...
    - go vet ./...
    - |
      SKIP_INSTALL={{.skip}}
      FORCE={{.force}}
      
      INSTALL_LINT=true
      if [ "$SKIP_INSTALL" = "true" ]; then
        INSTALL_LINT=false
      fi

      if [ "$INSTALL_LINT" = "true" ] && [ "$FORCE" != "true" ]; then
        if command -v golangci-lint &>/dev/null && [ "$(golangci-lint --version 2>/dev/null | awk -F'version ' '{print $2}' | awk '{print $1}')" = "$(echo "{{.GOLANGCI_LINT_VERSION}}" | sed 's/v//')" ]; then
          INSTALL_LINT=false
        fi
      fi

      if [ "$INSTALL_LINT" = "true" ]; then
        echo "Installing golangci-lint@{{.GOLANGCI_LINT_VERSION}}..."
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
      fi
      
      golangci-lint run
    - echo "All code quality checks completed" 