version: "3"

tasks:
  # Code quality tasks
  lint:
    desc: "Run linter (golangci-lint)"
    silent: true
    cmds:
    - golangci-lint run

  fix:
    desc: "Run linter and automatically fix issues"
    silent: true
    cmds:
    - echo "Running linter with --fix option..."
    - golangci-lint run --fix
    - echo "Linting and fixing complete."

  fmt:
    desc: Format code
    silent: true
    cmds:
    - go fmt ./...
    - echo "Code formatted successfully"

  vet:
    desc: Run go vet
    silent: true
    cmds:
    - go vet ./...
    - echo "Vet analysis completed"

  check:
    desc: Run all code quality checks
    silent: true
    cmds:
    - go fmt ./...
    - go vet ./...
    - golangci-lint run
    - echo "All code quality checks completed"

  gosec:
    desc: "Run gosec security scanner"
    silent: true
    cmds:
    - echo "Running gosec security scanner..."
    - gosec ./...

  all:
    desc: "Run ALL quality checks (fmt, vet, and aggressive linting) and apply all available fixes"
    silent: true
    cmds:
    - echo "Applying code formatting..."
    - go fmt ./...
    - echo "Running go vet analysis..."
    - go vet ./...
    - echo "Running aggressive linting and fixing..."
    - golangci-lint run --fix --max-issues-per-linter=0 --max-same-issues=0
    - echo "✅ All quality checks and fixes have been applied." 