// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"
)

type Querier interface {
	GetAdminUsers(ctx context.Context) ([]User, error)
	GetPendingVerificationUsers(ctx context.Context) ([]User, error)
	GetUser(ctx context.Context, id uint64) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
