env: docker

# Application settings
app:
  name: "Scaffold v1.0.0"
  version: "1.0.0"

http:
  host: app
  port: 12001

# Server configuration
server:
  shutdown_timeout: "30s"
  
  # Middleware configuration
  middleware:
    recover: true
    request_id: true
    logger: true
    cors: true
    logger_format: "[${time}] ${status} - ${method} ${path} - ${ip} - ${latency}\n"
  
  # CORS configuration
  cors:
    allow_origins: "http://localhost:3000,http://localhost:3001,http://localhost:8080,http://frontend:3000"
    allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
    allow_headers: "Origin,Content-Type,Accept,Authorization,X-Requested-With"
    allow_credentials: true
    max_age: 7200

db:
  mysql:
    host: mysql
    port: 3306
    user: scaffold
    password: bXlfc2VjdXJlX3Bhc3N3b3JkXzEyMw==
    database: user
  adminer:
    host: adminer
    port: 8888
    theme: nette

log:
  level: "info"
  loggers:
    console:
      driver: "console"
      enabled: true
      colors: true
      json_format: false
    file:
      driver: "file"
      enabled: true
      directory: "/app/logs"
      filename: "app.log"
      json_format: true
      max_size: 100
      max_backups: 3
      max_age: 7
      compress: true
    datadog_logger:
      driver: "datadog"
      enabled: true
      host: "datadog-agent"  # Assuming Datadog agent runs as a sidecar container
      port: 10518
      service: "scaffold"
      environment: "docker"
      source: "go"
      tags: "env:docker,service:scaffold,version:1.0.0,container:true"
      timeout: 10
      json_format: true 