env: docker
http:
  port: 8000
data:
  mysql:
    user: root:123456@tcp(mysql:3306)/user?charset=utf8mb4&parseTime=True&loc=Local
log:
  level: "info"
  loggers:
    console:
      driver: "console"
      enabled: true
      colors: true
      json_format: false 