env: local

# Application settings
app:
  name: "Scaffold v1.0.0"
  version: "1.0.0"

http:
  port: 8000

# Server configuration
server:
  shutdown_timeout: "30s"
  
  # Middleware configuration
  middleware:
    recover: true
    request_id: true
    logger: true
    cors: true
    logger_format: "[${time}] ${status} - ${method} ${path} - ${ip} - ${latency}\n"
  
  # CORS configuration
  cors:
    allow_origins: "http://localhost:3000,http://localhost:3001,http://localhost:8080,http://127.0.0.1:3000"
    allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
    allow_headers: "Origin,Content-Type,Accept,Authorization,X-Requested-With"
    allow_credentials: true
    max_age: 7200

db:
  mysql:
    host: 127.0.0.1
    port: 3306
    user: scaffold
    password: my_secure_password_123
    database: user

log:
  level: "debug"
  loggers:
    console:
      driver: "console"
      enabled: true
      colors: true
      json_format: false
    file:
      driver: "file"
      enabled: true
      directory: "logs"
      filename: "app.log"
      json_format: true
      max_size: 100
      max_backups: 3
      max_age: 7
      compress: true
    datadog_logger:
      driver: "datadog"
      enabled: true
      host: "127.0.0.1"
      port: 10518
      service: "scaffold"
      environment: "local"
      source: "go"
      tags: "env:local,service:scaffold,version:1.0.0"
      timeout: 5
      json_format: true
  # Future loggers can be easily added:
  # logdna_logger:
  #   enabled: false
  #   ingestion_key: ""
  #   hostname: "localhost"
