env: production

# Application settings
app:
  name: "Scaffold v1.0.0"
  version: "1.0.0"

http:
  port: 8080

# Server configuration
server:
  shutdown_timeout: "30s"
  
  # Middleware configuration
  middleware:
    recover: true
    request_id: true
    logger: false  # Using file logging instead
    cors: true
    logger_format: "[${time}] ${status} - ${method} ${path} - ${ip} - ${latency}\n"
  
  # CORS configuration
  cors:
    allow_origins: "https://yourdomain.com,https://api.yourdomain.com"
    allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
    allow_headers: "Origin,Content-Type,Accept,Authorization,X-Requested-With"
    allow_credentials: true
    max_age: 7200

security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: 1234

db:
  mysql:
    host: 127.0.0.1
    port: 3380
    user: scaffold
    password: 123456
    database: user
  redis:
    addr: 127.0.0.1:6350
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  level: "info"
  loggers:
    console:
      driver: "console"
      enabled: false
      colors: false
      json_format: true
    file:
      driver: "file"
      enabled: true
      directory: "/var/log/scaffold"
      filename: "app.log"
      json_format: true
      max_size: 100
      max_backups: 5
      max_age: 30
      compress: true
